# PyAutoGUI stub file for Pylance type checking
from typing import Tuple, Optional, Union, Any

__version__: str
FAILSAFE: bool

class Point:
    x: int
    y: int

def size() -> Tuple[int, int]: ...
def position() -> Point: ...
def moveTo(x: int, y: int) -> None: ...
def click(x: Optional[int] = None, y: Optional[int] = None, clicks: int = 1, interval: float = 0.0, button: str = 'left') -> None: ...
def scroll(clicks: int, x: Optional[int] = None, y: Optional[int] = None) -> None: ...
def press(key: str) -> None: ...
def write(message: str, interval: float = 0.0) -> None: ...
def screenshot() -> Any: ...